apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: aws.kubedb.com
    k8s.io/kind: ProviderConfigUsage
    k8s.io/resource: providerconfigusages
    k8s.io/version: v1beta1
  name: aws.kubedb.com-v1beta1-providerconfigusages
spec:
  resource:
    group: aws.kubedb.com
    kind: ProviderConfigUsage
    name: providerconfigusages
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: awskubedbcom-providerconfigusage-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:5dc13e09778e610a53f87d4cbfd63df443e75216775dfc466f0d7eb79062a354
    enforceQuota: false
