apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: aws.kubedb.com
    k8s.io/kind: ProviderConfig
    k8s.io/resource: providerconfigs
    k8s.io/version: v1beta1
  name: aws.kubedb.com-v1beta1-providerconfigs
spec:
  resource:
    group: aws.kubedb.com
    kind: ProviderConfig
    name: providerconfigs
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: awskubedbcom-providerconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:90367d97a8c6437cbbffe2dc305b16a86c69969aa287f4e7039101f1ca487c49
    enforceQuota: false
