apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: opsworks.aws.upbound.io
    k8s.io/kind: Application
    k8s.io/resource: applications
    k8s.io/version: v1beta1
  name: opsworks.aws.upbound.io-v1beta1-applications
spec:
  resource:
    group: opsworks.aws.upbound.io
    kind: Application
    name: applications
    scope: Cluster
    version: v1beta1
