apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: network.azure.upbound.io
    k8s.io/kind: VirtualHubRouteTableRoute
    k8s.io/resource: virtualhubroutetableroutes
    k8s.io/version: v1beta1
  name: network.azure.upbound.io-v1beta1-virtualhubroutetableroutes
spec:
  resource:
    group: network.azure.upbound.io
    kind: VirtualHubRouteTableRoute
    name: virtualhubroutetableroutes
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: networkazureupboundio-virtualhubroutetableroute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: bytebuilders-ui
      version: v0.4.18
    enforceQuota: false
