apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: image.toolkit.fluxcd.io
    k8s.io/kind: ImageUpdateAutomation
    k8s.io/resource: imageupdateautomations
    k8s.io/version: v1beta2
  name: image.toolkit.fluxcd.io-v1beta2-imageupdateautomations
spec:
  resource:
    group: image.toolkit.fluxcd.io
    kind: ImageUpdateAutomation
    name: imageupdateautomations
    scope: Namespaced
    version: v1beta2
  ui:
    editor:
      name: imagetoolkitfluxcdio-imageupdateautomation-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:feee6645eca337175c7357ab5e88eec015cc64a8bff0e873f7c9e1434f04a475
    enforceQuota: false
