apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: image.toolkit.fluxcd.io
    k8s.io/kind: ImageUpdateAutomation
    k8s.io/resource: imageupdateautomations
    k8s.io/version: v1beta2
  name: image.toolkit.fluxcd.io-v1beta2-imageupdateautomations
spec:
  resource:
    group: image.toolkit.fluxcd.io
    kind: ImageUpdateAutomation
    name: imageupdateautomations
    scope: Namespaced
    version: v1beta2
  ui:
    editor:
      name: imagetoolkitfluxcdio-imageupdateautomation-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8006c07d748c377e187656a74470ade26d51e544551e58275f62b0488fd35e25
    enforceQuota: false
