apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: dbformariadb.azure.upbound.io
    k8s.io/kind: Configuration
    k8s.io/resource: configurations
    k8s.io/version: v1beta1
  name: dbformariadb.azure.upbound.io-v1beta1-configurations
spec:
  resource:
    group: dbformariadb.azure.upbound.io
    kind: Configuration
    name: configurations
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: dbformariadbazureupboundio-configuration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: bytebuilders-ui
      version: v0.4.18
    enforceQuota: false
