apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gcp.kubedb.com
    k8s.io/kind: StoreConfig
    k8s.io/resource: storeconfigs
    k8s.io/version: v1alpha1
  name: gcp.kubedb.com-v1alpha1-storeconfigs
spec:
  resource:
    group: gcp.kubedb.com
    kind: StoreConfig
    name: storeconfigs
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: gcpkubedbcom-storeconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3d4a2200f12a69cf9dfd824dbb6ac952df0f1e7da737e6a2d26b84ebaadad9bc
    enforceQuota: false
