apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: config.gateway.open-cluster-management.io
    k8s.io/kind: ClusterGatewayConfiguration
    k8s.io/resource: clustergatewayconfigurations
    k8s.io/version: v1alpha1
  name: config.gateway.open-cluster-management.io-v1alpha1-clustergatewayconfigurations
spec:
  resource:
    group: config.gateway.open-cluster-management.io
    kind: ClusterGatewayConfiguration
    name: clustergatewayconfigurations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: configgatewayopenclustermanagementio-clustergatewayconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3adf8d3bdb1a64231e6a7cd6b0c92fd1affcbc1c53e57dba5054b7c8281ba2be
    enforceQuota: false
