apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: apigateway.aws.upbound.io
    k8s.io/kind: Deployment
    k8s.io/resource: deployments
    k8s.io/version: v1beta1
  name: apigateway.aws.upbound.io-v1beta1-deployments
spec:
  resource:
    group: apigateway.aws.upbound.io
    kind: Deployment
    name: deployments
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: apigatewayawsupboundio-deployment-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: bytebuilders-ui
      version: v0.4.18
    enforceQuota: false
