apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: route53.aws.upbound.io
    k8s.io/kind: ResolverConfig
    k8s.io/resource: resolverconfigs
    k8s.io/version: v1beta1
  name: route53.aws.upbound.io-v1beta1-resolverconfigs
spec:
  resource:
    group: route53.aws.upbound.io
    kind: ResolverConfig
    name: resolverconfigs
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: route53awsupboundio-resolverconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: bytebuilders-ui
      version: v0.4.18
    enforceQuota: false
