apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: voyager.appscode.com
    k8s.io/kind: Ingress
    k8s.io/resource: ingresses
    k8s.io/version: v1beta1
  name: voyager.appscode.com-v1beta1-ingresses
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/voyager.appscode.com/ingresses.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/voyager.appscode.com/ingresses.png
    type: image/png
  resource:
    group: voyager.appscode.com
    kind: Ingress
    name: ingresses
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: voyagerappscodecom-ingress-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:22e6c9711bd513975fa8b0538323cfb728445530c25b1dbe1fdead28ad58b556
    enforceQuota: false
