apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: stash.appscode.com
    k8s.io/kind: BackupConfiguration
    k8s.io/resource: backupconfigurations
    k8s.io/version: v1beta1
  name: stash.appscode.com-v1beta1-backupconfigurations
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/backupconfigurations.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/stash.appscode.com/backupconfigurations.png
    type: image/png
  resource:
    group: stash.appscode.com
    kind: BackupConfiguration
    name: backupconfigurations
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: stashappscodecom-backupconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:80c01d22d58dca631e4cd7e16b7cd4ceb5d03db82a9f7716f11ab2a1b5f13c0d
    enforceQuota: false
