apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbforpostgresql.azure.kubedb.com
    k8s.io/kind: FlexibleServerConfiguration
    k8s.io/resource: flexibleserverconfigurations
    k8s.io/version: v1alpha1
  name: dbforpostgresql.azure.kubedb.com-v1alpha1-flexibleserverconfigurations
spec:
  resource:
    group: dbforpostgresql.azure.kubedb.com
    kind: FlexibleServerConfiguration
    name: flexibleserverconfigurations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbforpostgresqlazurekubedbcom-flexibleserverconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:cefafce341db5523fc3a7f3f6e7dc96a392d69e1c8d72c458c45e24091e336b5
    enforceQuota: false
