apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: dbforpostgresql.azure.kubedb.com
    k8s.io/kind: FlexibleServerConfiguration
    k8s.io/resource: flexibleserverconfigurations
    k8s.io/version: v1alpha1
  name: dbforpostgresql.azure.kubedb.com-v1alpha1-flexibleserverconfigurations
spec:
  resource:
    group: dbforpostgresql.azure.kubedb.com
    kind: FlexibleServerConfiguration
    name: flexibleserverconfigurations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbforpostgresqlazurekubedbcom-flexibleserverconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:fdb656f52b90adf7da28447a8e1a96c39088f15a3efbb211795e94d685894986
    enforceQuota: false
