apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gcp.kubedb.com
    k8s.io/kind: ProviderConfigUsage
    k8s.io/resource: providerconfigusages
    k8s.io/version: v1beta1
  name: gcp.kubedb.com-v1beta1-providerconfigusages
spec:
  resource:
    group: gcp.kubedb.com
    kind: ProviderConfigUsage
    name: providerconfigusages
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: gcpkubedbcom-providerconfigusage-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3524ff0c696466496bceb007793a94f3481b1edda3cf7ff27bd78fc88d3cc35e
    enforceQuota: false
