apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceBlockDefinition
metadata:
  labels:
    k8s.io/group: ""
    k8s.io/kind: ConfigMap
    k8s.io/resource: configmaps
    k8s.io/version: v1
  name: core-v1-configmaps
spec:
  blocks:
  - actions:
      create: Never
    displayMode: List
    kind: Connection
    name: Pods
    query:
      byLabel: config
      type: GraphQL
    ref:
      group: ""
      kind: Pod
  resource:
    group: ""
    kind: ConfigMap
    name: configmaps
    scope: Namespaced
    version: v1
