apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: servicediscovery.aws.upbound.io
    k8s.io/kind: Service
    k8s.io/resource: services
    k8s.io/version: v1beta1
  name: servicediscovery.aws.upbound.io-v1beta1-services
spec:
  resource:
    group: servicediscovery.aws.upbound.io
    kind: Service
    name: services
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: servicediscoveryawsupboundio-service-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: bytebuilders-ui
      version: v0.4.18
    enforceQuota: false
