apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceBlockDefinition
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kubedb.com
    k8s.io/kind: MongoDB
    k8s.io/resource: mongodbs
    k8s.io/version: v1alpha2
  name: kubedb.com-v1alpha2-security
spec:
  blocks:
  - actions:
      create: Never
    displayMode: List
    kind: Connection
    name: ServiceAccount
    query:
      byLabel: offshoot
      type: GraphQL
    ref:
      group: ""
      kind: ServiceAccount
  - actions:
      create: Never
    displayMode: List
    kind: Connection
    name: Roles
    query:
      byLabel: offshoot
      type: GraphQL
    ref:
      group: rbac.authorization.k8s.io
      kind: Role
  - actions:
      create: Never
    displayMode: List
    kind: Connection
    name: RoleBindings
    query:
      byLabel: offshoot
      type: GraphQL
    ref:
      group: rbac.authorization.k8s.io
      kind: RoleBinding
  - actions:
      create: Never
    displayMode: List
    kind: Connection
    name: Certificates
    query:
      byLabel: offshoot
      type: GraphQL
    ref:
      group: cert-manager.io
      kind: Certificate
  - actions:
      create: Never
    displayMode: List
    kind: Connection
    name: Issuer
    query:
      byLabel: cert_issuer
      type: GraphQL
    ref:
      group: cert-manager.io
      kind: Issuer
  - actions:
      create: Never
    displayMode: List
    kind: Connection
    name: Cluster Issuer
    query:
      byLabel: cert_issuer
      type: GraphQL
    ref:
      group: cert-manager.io
      kind: ClusterIssuer
  - actions:
      create: Never
    displayMode: List
    kind: Connection
    name: Pod Security Policies
    query:
      byLabel: policy
      type: GraphQL
    ref:
      group: policy
      kind: PodSecurityPolicy
