apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: monitoring.coreos.com
    k8s.io/kind: Prometheus
    k8s.io/resource: prometheuses
    k8s.io/version: v1
  name: monitoring.coreos.com-v1-prometheuses
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/monitoring.coreos.com/prometheuses.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/monitoring.coreos.com/prometheuses.png
    type: image/png
  resource:
    group: monitoring.coreos.com
    kind: Prometheus
    name: prometheuses
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: monitoringcoreoscom-prometheus-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:d38953e5845e6317798bad3097dbd9828a083e17d7514ce6e2c75e10879da16b
    enforceQuota: false
