apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: networkfirewall.aws.upbound.io
    k8s.io/kind: LoggingConfiguration
    k8s.io/resource: loggingconfigurations
    k8s.io/version: v1beta1
  name: networkfirewall.aws.upbound.io-v1beta1-loggingconfigurations
spec:
  resource:
    group: networkfirewall.aws.upbound.io
    kind: LoggingConfiguration
    name: loggingconfigurations
    scope: Cluster
    version: v1beta1
