apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: logging.gcp.upbound.io
    k8s.io/kind: ProjectBucketConfig
    k8s.io/resource: projectbucketconfigs
    k8s.io/version: v1beta1
  name: logging.gcp.upbound.io-v1beta1-projectbucketconfigs
spec:
  resource:
    group: logging.gcp.upbound.io
    kind: ProjectBucketConfig
    name: projectbucketconfigs
    scope: Cluster
    version: v1beta1
