apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kinesisanalyticsv2.aws.upbound.io
    k8s.io/kind: Application
    k8s.io/resource: applications
    k8s.io/version: v1beta1
  name: kinesisanalyticsv2.aws.upbound.io-v1beta1-applications
spec:
  resource:
    group: kinesisanalyticsv2.aws.upbound.io
    kind: Application
    name: applications
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: kinesisanalyticsv2awsupboundio-application-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: bytebuilders-ui
      version: v0.4.18
    enforceQuota: false
