apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.networking.k8s.io
    k8s.io/kind: TLSRoute
    k8s.io/resource: tlsroutes
    k8s.io/version: v1alpha2
  name: gateway.networking.k8s.io-v1alpha2-tlsroutes
spec:
  resource:
    group: gateway.networking.k8s.io
    kind: TLSRoute
    name: tlsroutes
    scope: Namespaced
    version: v1alpha2
  ui:
    editor:
      name: gatewaynetworkingk8sio-tlsroute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:4c33e07ca13a6b0ff7bd7978977c9e75ea38c3feebfecf516c83bd3b0ecbfe1a
    enforceQuota: false
