apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: pkg.crossplane.io
    k8s.io/kind: ControllerConfig
    k8s.io/resource: controllerconfigs
    k8s.io/version: v1alpha1
  name: pkg.crossplane.io-v1alpha1-controllerconfigs
spec:
  resource:
    group: pkg.crossplane.io
    kind: ControllerConfig
    name: controllerconfigs
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: pkgcrossplaneio-controllerconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:1457bc9ac29cb660dd30cfc07d7ac356e0be86e2dd37bdf8667c68efb4b85bb9
    enforceQuota: false
