apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ssm.aws.upbound.io
    k8s.io/kind: ServiceSetting
    k8s.io/resource: servicesettings
    k8s.io/version: v1beta1
  name: ssm.aws.upbound.io-v1beta1-servicesettings
spec:
  resource:
    group: ssm.aws.upbound.io
    kind: ServiceSetting
    name: servicesettings
    scope: Cluster
    version: v1beta1
