apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceTableDefinition
metadata:
  labels:
    k8s.io/group: networking.k8s.io
    k8s.io/kind: Ingress
    k8s.io/resource: ingresses
    k8s.io/version: v1
  name: networking.k8s.io-v1-ingresses
spec:
  defaultView: true
  resource:
    group: networking.k8s.io
    kind: Ingress
    name: ingresses
    scope: Namespaced
    version: v1
