apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: dbformysql.azure.kubedb.com
    k8s.io/kind: FlexibleServerConfiguration
    k8s.io/resource: flexibleserverconfigurations
    k8s.io/version: v1alpha1
  name: dbformysql.azure.kubedb.com-v1alpha1-flexibleserverconfigurations
spec:
  resource:
    group: dbformysql.azure.kubedb.com
    kind: FlexibleServerConfiguration
    name: flexibleserverconfigurations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: dbformysqlazurekubedbcom-flexibleserverconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:753488c1fc2977fdb7904b1518a994934db101b215e900fd6157f4582a3d7d4e
    enforceQuota: false
