apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceOutline
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: monitoring.coreos.com
    k8s.io/kind: Prometheus
    k8s.io/resource: prometheuses
    k8s.io/version: v1
  name: monitoring.coreos.com-v1-prometheuses
spec:
  defaultLayout: true
  pages:
  - name: Overview
    sections:
    - blocks:
      - actions:
          create: Never
        displayMode: List
        kind: Connection
        name: Pods
        query:
          byLabel: offshoot
          type: GraphQL
        ref:
          group: ""
          kind: Pod
      - actions:
          create: Never
        displayMode: List
        kind: Connection
        name: Services
        query:
          byLabel: exposed_by
          type: GraphQL
        ref:
          group: ""
          kind: Service
  - name: Monitoring
    sections:
    - blocks:
      - actions:
          create: Always
        displayMode: List
        kind: Connection
        name: Service Monitors
        query:
          byLabel: monitored_by
          type: GraphQL
        ref:
          group: monitoring.coreos.com
          kind: ServiceMonitor
      - actions:
          create: Always
        displayMode: List
        kind: Connection
        name: Pod Monitors
        query:
          byLabel: monitored_by
          type: GraphQL
        ref:
          group: monitoring.coreos.com
          kind: PodMonitor
  resource:
    group: monitoring.coreos.com
    kind: Prometheus
    name: prometheuses
    scope: Namespaced
    version: v1
