apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceTableDefinition
metadata:
  labels:
    k8s.io/group: monitoring.coreos.com
    k8s.io/kind: PrometheusAgent
    k8s.io/resource: prometheusagents
    k8s.io/version: v1alpha1
  name: monitoring.coreos.com-v1alpha1-prometheusagents
spec:
  defaultView: true
  resource:
    group: monitoring.coreos.com
    kind: PrometheusAgent
    name: prometheusagents
    scope: Namespaced
    version: v1alpha1
