apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceOutline
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: apps
    k8s.io/kind: Deployment
    k8s.io/resource: deployments
    k8s.io/version: v1
  name: apps-v1-deployments
spec:
  defaultLayout: true
  pages:
  - blocks:
    - kind: Block
      name: apps-v1-deployments
    name: Basic
  - blocks:
    - kind: Block
      name: stash.appscode.com-v1-backup
    name: Backups
  - blocks:
    - kind: Block
      name: monitoring.coreos.com-v1-monitoring
    name: Monitoring
  resource:
    group: apps
    kind: Deployment
    name: deployments
    scope: Namespaced
    version: v1
