apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: extensions
    k8s.io/kind: Ingress
    k8s.io/resource: ingresses
    k8s.io/version: v1beta1
  name: extensions-v1beta1-ingresses
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/extensions/ingresses.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/extensions/ingresses.png
    type: image/png
  resource:
    group: extensions
    kind: Ingress
    name: ingresses
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: extensions-ingress-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: bytebuilders-ui
      version: sha256:df23514992fa05753ca2025bb61e9e0c7b1e77d71e11261bf04613f190aa3c67
