apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: extensions
    k8s.io/kind: Ingress
    k8s.io/resource: ingresses
    k8s.io/version: v1beta1
  name: extensions-v1beta1-ingresses
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/extensions/ingresses.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/extensions/ingresses.png
    type: image/png
  resource:
    group: extensions
    kind: Ingress
    name: ingresses
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: extensions-ingress-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8c91cb7ab23983cd7bde2e610768ba737021a869a768d46b4dad9f7a90849ac6
    enforceQuota: false
