apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: elasticbeanstalk.aws.upbound.io
    k8s.io/kind: ConfigurationTemplate
    k8s.io/resource: configurationtemplates
    k8s.io/version: v1beta1
  name: elasticbeanstalk.aws.upbound.io-v1beta1-configurationtemplates
spec:
  resource:
    group: elasticbeanstalk.aws.upbound.io
    kind: ConfigurationTemplate
    name: configurationtemplates
    scope: Cluster
    version: v1beta1
