apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: lambda.aws.upbound.io
    k8s.io/kind: ProvisionedConcurrencyConfig
    k8s.io/resource: provisionedconcurrencyconfigs
    k8s.io/version: v1beta1
  name: lambda.aws.upbound.io-v1beta1-provisionedconcurrencyconfigs
spec:
  resource:
    group: lambda.aws.upbound.io
    kind: ProvisionedConcurrencyConfig
    name: provisionedconcurrencyconfigs
    scope: Cluster
    version: v1beta1
