apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: pkg.crossplane.io
    k8s.io/kind: Configuration
    k8s.io/resource: configurations
    k8s.io/version: v1
  name: pkg.crossplane.io-v1-configurations
spec:
  resource:
    group: pkg.crossplane.io
    kind: Configuration
    name: configurations
    scope: Cluster
    version: v1
  ui:
    editor:
      name: pkgcrossplaneio-configuration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a5223604796e111c02105a35c0a69f270deb589fa62a03f0f8dc99b74f54b399
    enforceQuota: false
