apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: insights.azure.upbound.io
    k8s.io/kind: ApplicationInsights
    k8s.io/resource: applicationinsights
    k8s.io/version: v1beta1
  name: insights.azure.upbound.io-v1beta1-applicationinsights
spec:
  resource:
    group: insights.azure.upbound.io
    kind: ApplicationInsights
    name: applicationinsights
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: insightsazureupboundio-applicationinsights-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: bytebuilders-ui
      version: v0.4.18
    enforceQuota: false
