apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: insights.azure.upbound.io
    k8s.io/kind: ApplicationInsightsWorkbookTemplate
    k8s.io/resource: applicationinsightsworkbooktemplates
    k8s.io/version: v1beta1
  name: insights.azure.upbound.io-v1beta1-applicationinsightsworkbooktemplates
spec:
  resource:
    group: insights.azure.upbound.io
    kind: ApplicationInsightsWorkbookTemplate
    name: applicationinsightsworkbooktemplates
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: insightsazureupboundio-applicationinsightsworkbooktemplate-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: bytebuilders-ui
      version: v0.4.18
    enforceQuota: false
