apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: kafka.aws.kubedb.com
    k8s.io/kind: Configuration
    k8s.io/resource: configurations
    k8s.io/version: v1alpha1
  name: kafka.aws.kubedb.com-v1alpha1-configurations
spec:
  resource:
    group: kafka.aws.kubedb.com
    kind: Configuration
    name: configurations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: kafkaawskubedbcom-configuration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:2c7546bcd00d1008bf51cf2cfa583fd5a7f9f7735e5f095e2e5bb4a34fe520b4
    enforceQuota: false
