apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ec2.aws.kubedb.com
    k8s.io/kind: Route
    k8s.io/resource: routes
    k8s.io/version: v1alpha1
  name: ec2.aws.kubedb.com-v1alpha1-routes
spec:
  resource:
    group: ec2.aws.kubedb.com
    kind: Route
    name: routes
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: ec2awskubedbcom-route-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:9419912e84c05d0c4b16d8d297c957aa23a96fe675b80932d68a2d62b8b54b8f
    enforceQuota: false
