apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: networking.k8s.io
    k8s.io/kind: Ingress
    k8s.io/resource: ingresses
    k8s.io/version: v1beta1
  name: networking.k8s.io-v1beta1-ingresses
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/networking.k8s.io/ingresses.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/networking.k8s.io/ingresses.png
    type: image/png
  resource:
    group: networking.k8s.io
    kind: Ingress
    name: ingresses
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: networkingk8sio-ingress-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:9871e3085c4b4bd9acf97c7cc2667c9d72bdec393704b18e2f7d7ed2b929b8ef
    enforceQuota: false
