apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceTableDefinition
metadata:
  labels:
    k8s.io/group: aws.kubedb.com
    k8s.io/kind: StoreConfig
    k8s.io/resource: storeconfigs
    k8s.io/version: v1alpha1
  name: aws.kubedb.com-v1alpha1-storeconfigs
spec:
  defaultView: true
  resource:
    group: aws.kubedb.com
    kind: StoreConfig
    name: storeconfigs
    scope: Cluster
    version: v1alpha1
