apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: timeseriesinsights.azure.upbound.io
    k8s.io/kind: Gen2Environment
    k8s.io/resource: gen2environments
    k8s.io/version: v1beta1
  name: timeseriesinsights.azure.upbound.io-v1beta1-gen2environments
spec:
  resource:
    group: timeseriesinsights.azure.upbound.io
    kind: Gen2Environment
    name: gen2environments
    scope: Cluster
    version: v1beta1
