apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: gateway.voyagermesh.com
    k8s.io/kind: KafkaRoute
    k8s.io/resource: kafkaroutes
    k8s.io/version: v1alpha1
  name: gateway.voyagermesh.com-v1alpha1-kafkaroutes
spec:
  resource:
    group: gateway.voyagermesh.com
    kind: KafkaRoute
    name: kafkaroutes
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayvoyagermeshcom-kafkaroute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:e2d2fc55c62ad6a679a5476d9aa5184c8c10dedd0a4e4ed8f07b0205f94874fb
    enforceQuota: false
