apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: gateway.voyagermesh.com
    k8s.io/kind: MongoDBRoute
    k8s.io/resource: mongodbroutes
    k8s.io/version: v1alpha1
  name: gateway.voyagermesh.com-v1alpha1-mongodbroutes
spec:
  resource:
    group: gateway.voyagermesh.com
    kind: MongoDBRoute
    name: mongodbroutes
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayvoyagermeshcom-mongodbroute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:a8e3f36f61c35868ca2d3fce48a2758e46456182375a775c015143671db7fc06
    enforceQuota: false
