apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: gateway.voyagermesh.com
    k8s.io/kind: MSSQLServerRoute
    k8s.io/resource: mssqlserverroutes
    k8s.io/version: v1alpha1
  name: gateway.voyagermesh.com-v1alpha1-mssqlserverroutes
spec:
  resource:
    group: gateway.voyagermesh.com
    kind: MSSQLServerRoute
    name: mssqlserverroutes
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: gatewayvoyagermeshcom-mssqlserverroute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:24dee12fd907fb548ff9d63d20b07bc38dd36870a5312b63c8926bb0ee7a403c
    enforceQuota: false
