apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: PgBouncerSettings
    k8s.io/resource: pgbouncersettings
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-pgbouncersettings
spec:
  resource:
    group: ui.kubedb.com
    kind: PgBouncerSettings
    name: pgbouncersettings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-pgbouncersettings-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:e1671572731333425c4f1148c911664f6ccff860325f5a17d98fe64a460345dd
    enforceQuota: false
