apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: PostgresSettings
    k8s.io/resource: postgressettings
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-postgressettings
spec:
  resource:
    group: ui.kubedb.com
    kind: PostgresSettings
    name: postgressettings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-postgressettings-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:cb3426a93e8b1e0c5bf9bdd38046db93a46da2f30bad1a47dea899596530c317
    enforceQuota: false
