apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: ui.kubedb.com
    k8s.io/kind: ProxySQLSettings
    k8s.io/resource: proxysqlsettings
    k8s.io/version: v1alpha1
  name: ui.kubedb.com-v1alpha1-proxysqlsettings
spec:
  resource:
    group: ui.kubedb.com
    kind: ProxySQLSettings
    name: proxysqlsettings
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: uikubedbcom-proxysqlsettings-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:82f9fbd0b46436d8a953b79fa4221440336b499d20681698041ee47c61081db8
    enforceQuota: false
