apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: azure.kubedb.com
    k8s.io/kind: StoreConfig
    k8s.io/resource: storeconfigs
    k8s.io/version: v1alpha1
  name: azure.kubedb.com-v1alpha1-storeconfigs
spec:
  resource:
    group: azure.kubedb.com
    kind: StoreConfig
    name: storeconfigs
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: azurekubedbcom-storeconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:bc1e33fc3018fcdcb3649845bdf84712e0ac4f9b64b949c065b57095a348d9cd
    enforceQuota: false
