apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: cdn.azure.upbound.io
    k8s.io/kind: FrontdoorRoute
    k8s.io/resource: frontdoorroutes
    k8s.io/version: v1beta1
  name: cdn.azure.upbound.io-v1beta1-frontdoorroutes
spec:
  resource:
    group: cdn.azure.upbound.io
    kind: FrontdoorRoute
    name: frontdoorroutes
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: cdnazureupboundio-frontdoorroute-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: bytebuilders-ui
      version: v0.4.18
    enforceQuota: false
