apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: apigee.gcp.upbound.io
    k8s.io/kind: Environment
    k8s.io/resource: environments
    k8s.io/version: v1beta1
  name: apigee.gcp.upbound.io-v1beta1-environments
spec:
  resource:
    group: apigee.gcp.upbound.io
    kind: Environment
    name: environments
    scope: Cluster
    version: v1beta1
