apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: amp.aws.upbound.io
    k8s.io/kind: AlertManagerDefinition
    k8s.io/resource: alertmanagerdefinitions
    k8s.io/version: v1beta1
  name: amp.aws.upbound.io-v1beta1-alertmanagerdefinitions
spec:
  resource:
    group: amp.aws.upbound.io
    kind: AlertManagerDefinition
    name: alertmanagerdefinitions
    scope: Cluster
    version: v1beta1
