apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: aws.upbound.io
    k8s.io/kind: ProviderConfigUsage
    k8s.io/resource: providerconfigusages
    k8s.io/version: v1beta1
  name: aws.upbound.io-v1beta1-providerconfigusages
spec:
  resource:
    group: aws.upbound.io
    kind: ProviderConfigUsage
    name: providerconfigusages
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: awsupboundio-providerconfigusage-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: bytebuilders-ui
      version: v0.4.18
    enforceQuota: false
