apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: core.kubestash.com
    k8s.io/kind: BackupConfiguration
    k8s.io/resource: backupconfigurations
    k8s.io/version: v1alpha1
  name: core.kubestash.com-v1alpha1-backupconfigurations
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupconfigurations.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/core.kubestash.com/backupconfigurations.png
    type: image/png
  resource:
    group: core.kubestash.com
    kind: BackupConfiguration
    name: backupconfigurations
    scope: Namespaced
    version: v1alpha1
  ui:
    editor:
      name: corekubestashcom-backupconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:23fcfd22cfc3c4dfb17cdbfc47c8fbdf0c4fcba0ab6b2d13a0a842f69e000334
    enforceQuota: false
    options:
      name: corekubestashcom-backupconfiguration-editor-options
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:c27ff8cdb467f3dd6760e4e83ae560904b42573825fdd186af7ee48202648ee0
