apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceTableDefinition
metadata:
  creationTimestamp: null
  name: ui.kubedb.com-v1alpha1-perconaxtradbsettings-settings
spec:
  columns:
  - name: Name
    pathTemplate: '{{ .name }}'
    priority: 3
    type: string
  - name: Current Value
    pathTemplate: '{{ .currentValue }}'
    priority: 3
    type: string
  - name: Default Value
    pathTemplate: '{{ .defaultValue }}'
    priority: 3
    type: string
  - name: Unit
    pathTemplate: '{{ .unit }}'
    priority: 3
    type: string
  - name: Source
    pathTemplate: '{{ .source }}'
    priority: 3
    type: string
  defaultView: false
