apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: apigatewayv2.aws.upbound.io
    k8s.io/kind: Deployment
    k8s.io/resource: deployments
    k8s.io/version: v1beta1
  name: apigatewayv2.aws.upbound.io-v1beta1-deployments
spec:
  resource:
    group: apigatewayv2.aws.upbound.io
    kind: Deployment
    name: deployments
    scope: Cluster
    version: v1beta1
