apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: apigatewayv2.aws.upbound.io
    k8s.io/kind: Route
    k8s.io/resource: routes
    k8s.io/version: v1beta1
  name: apigatewayv2.aws.upbound.io-v1beta1-routes
spec:
  resource:
    group: apigatewayv2.aws.upbound.io
    kind: Route
    name: routes
    scope: Cluster
    version: v1beta1
