apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: appstream.aws.upbound.io
    k8s.io/kind: DirectoryConfig
    k8s.io/resource: directoryconfigs
    k8s.io/version: v1beta1
  name: appstream.aws.upbound.io-v1beta1-directoryconfigs
spec:
  resource:
    group: appstream.aws.upbound.io
    kind: DirectoryConfig
    name: directoryconfigs
    scope: Cluster
    version: v1beta1
