apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: cloudfront.aws.upbound.io
    k8s.io/kind: RealtimeLogConfig
    k8s.io/resource: realtimelogconfigs
    k8s.io/version: v1beta1
  name: cloudfront.aws.upbound.io-v1beta1-realtimelogconfigs
spec:
  resource:
    group: cloudfront.aws.upbound.io
    kind: RealtimeLogConfig
    name: realtimelogconfigs
    scope: Cluster
    version: v1beta1
