apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: search.azure.upbound.io
    k8s.io/kind: Service
    k8s.io/resource: services
    k8s.io/version: v1beta1
  name: search.azure.upbound.io-v1beta1-services
spec:
  resource:
    group: search.azure.upbound.io
    kind: Service
    name: services
    scope: Cluster
    version: v1beta1
