apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: notebooks.gcp.upbound.io
    k8s.io/kind: Environment
    k8s.io/resource: environments
    k8s.io/version: v1beta1
  name: notebooks.gcp.upbound.io-v1beta1-environments
spec:
  resource:
    group: notebooks.gcp.upbound.io
    kind: Environment
    name: environments
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: notebooksgcpupboundio-environment-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: bytebuilders-ui
      version: v0.4.18
    enforceQuota: false
