apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: metrics.appscode.com
    k8s.io/kind: MetricsConfiguration
    k8s.io/resource: metricsconfigurations
    k8s.io/version: v1alpha1
  name: metrics.appscode.com-v1alpha1-metricsconfigurations
spec:
  resource:
    group: metrics.appscode.com
    kind: MetricsConfiguration
    name: metricsconfigurations
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: metricsappscodecom-metricsconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:11dd79e18863607782913fc8d50130bfd57cc3e90d5c716dc964be74fee93f65
    enforceQuota: false
