apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceTableDefinition
metadata:
  labels:
    k8s.io/group: monitoring.coreos.com
    k8s.io/kind: Alertmanager
    k8s.io/resource: alertmanagers
    k8s.io/version: v1
  name: monitoring.coreos.com-v1-alertmanagers
spec:
  defaultView: true
  resource:
    group: monitoring.coreos.com
    kind: Alertmanager
    name: alertmanagers
    scope: Namespaced
    version: v1
