apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceTableDefinition
metadata:
  labels:
    k8s.io/group: monitoring.coreos.com
    k8s.io/kind: PrometheusRule
    k8s.io/resource: prometheusrules
    k8s.io/version: v1
  name: monitoring.coreos.com-v1-prometheusrules
spec:
  defaultView: true
  resource:
    group: monitoring.coreos.com
    kind: PrometheusRule
    name: prometheusrules
    scope: Namespaced
    version: v1
