apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: s3.aws.upbound.io
    k8s.io/kind: BucketReplicationConfiguration
    k8s.io/resource: bucketreplicationconfigurations
    k8s.io/version: v1beta1
  name: s3.aws.upbound.io-v1beta1-bucketreplicationconfigurations
spec:
  resource:
    group: s3.aws.upbound.io
    kind: BucketReplicationConfiguration
    name: bucketreplicationconfigurations
    scope: Cluster
    version: v1beta1
  ui:
    editor:
      name: s3awsupboundio-bucketreplicationconfiguration-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: bytebuilders-ui
      version: v0.4.18
    enforceQuota: false
