apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: s3.aws.upbound.io
    k8s.io/kind: BucketRequestPaymentConfiguration
    k8s.io/resource: bucketrequestpaymentconfigurations
    k8s.io/version: v1beta1
  name: s3.aws.upbound.io-v1beta1-bucketrequestpaymentconfigurations
spec:
  resource:
    group: s3.aws.upbound.io
    kind: BucketRequestPaymentConfiguration
    name: bucketrequestpaymentconfigurations
    scope: Cluster
    version: v1beta1
