apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceTableDefinition
metadata:
  labels:
    k8s.io/group: gateway.voyagermesh.com
    k8s.io/kind: MSSQLServerRoute
    k8s.io/resource: mssqlserverroutes
    k8s.io/version: v1alpha1
  name: gateway.voyagermesh.com-v1alpha1-mssqlserverroutes
spec:
  defaultView: true
  resource:
    group: gateway.voyagermesh.com
    kind: MSSQLServerRoute
    name: mssqlserverroutes
    scope: Namespaced
    version: v1alpha1
