apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: image.toolkit.fluxcd.io
    k8s.io/kind: ImageUpdateAutomation
    k8s.io/resource: imageupdateautomations
    k8s.io/version: v1beta1
  name: image.toolkit.fluxcd.io-v1beta1-imageupdateautomations
spec:
  resource:
    group: image.toolkit.fluxcd.io
    kind: ImageUpdateAutomation
    name: imageupdateautomations
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: imagetoolkitfluxcdio-imageupdateautomation-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8db2b57e0f897d33732fa22b8999f43ae3717dcecccdd59f2cb4acbc57241cb9
    enforceQuota: false
