apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: image.toolkit.fluxcd.io
    k8s.io/kind: ImageUpdateAutomation
    k8s.io/resource: imageupdateautomations
    k8s.io/version: v1beta1
  name: image.toolkit.fluxcd.io-v1beta1-imageupdateautomations
spec:
  resource:
    group: image.toolkit.fluxcd.io
    kind: ImageUpdateAutomation
    name: imageupdateautomations
    scope: Namespaced
    version: v1beta1
  ui:
    editor:
      name: imagetoolkitfluxcdio-imageupdateautomation-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:8445050abb1fdefdb91b24e5b55b2c7b3fed9f7e35e655ca4d1c696d7c3d25af
    enforceQuota: false
