apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  creationTimestamp: null
  labels:
    k8s.io/group: spring.azure.upbound.io
    k8s.io/kind: CloudApplicationLiveView
    k8s.io/resource: cloudapplicationliveviews
    k8s.io/version: v1beta1
  name: spring.azure.upbound.io-v1beta1-cloudapplicationliveviews
spec:
  resource:
    group: spring.azure.upbound.io
    kind: CloudApplicationLiveView
    name: cloudapplicationliveviews
    scope: Cluster
    version: v1beta1
