apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: secrets.crossplane.io
    k8s.io/kind: StoreConfig
    k8s.io/resource: storeconfigs
    k8s.io/version: v1alpha1
  name: secrets.crossplane.io-v1alpha1-storeconfigs
spec:
  resource:
    group: secrets.crossplane.io
    kind: StoreConfig
    name: storeconfigs
    scope: Cluster
    version: v1alpha1
  ui:
    editor:
      name: secretscrossplaneio-storeconfig-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:3e57799ac260b254624eb0919203d79411aee4151417da1993af6ccd454bd74d
    enforceQuota: false
