apiVersion: ui.k8s.appscode.com/v1alpha1
kind: ResourceEditor
metadata:
  labels:
    k8s.io/group: apps
    k8s.io/kind: Deployment
    k8s.io/resource: deployments
    k8s.io/version: v1
  name: apps-v1-deployments
spec:
  icons:
  - src: https://cdn.appscode.com/k8s/icons/apps/deployments.svg
    type: image/svg+xml
  - src: https://cdn.appscode.com/k8s/icons/apps/deployments.png
    type: image/png
  resource:
    group: apps
    kind: Deployment
    name: deployments
    scope: Namespaced
    version: v1
  ui:
    editor:
      name: apps-deployment-editor
      sourceRef:
        apiGroup: source.toolkit.fluxcd.io
        kind: HelmRepository
        name: appscode-charts-oci
      version: sha256:ce9325c4a0e96133649b145b74d9f14c571bf3c525b46cfe5758ab79923b97ac
    enforceQuota: false
